COMMONSENSE_MAPPING = {
	'Antonym': 'is antonym of',
	'AtLocation': 'is at location',
	'CapableOf': 'is capable of',
	'Causes': 'causes',
	'CausesDesire': 'causes desire',
	'CreatedBy': 'is created by',
	'DefinedAs': 'is defined as',
	'DerivedFrom': 'is derived from',
	'Desires': 'desires',
	'DistinctFrom': 'is distinct from',
	'Entails': 'entails',
	'EtymologicallyDerivedFrom': 'is etymologically derived from',
	'EtymologicallyRelatedTo': 'is etymologically related to',
	'fe:ExcludesFE': 'excludes frame element',
	'FormOf': 'is form of',
	'HasA': 'has a',
	'HasContext': 'has context',
	'HasFirstSubevent': 'has first subevent',
	'HasFrameElement': 'has frame element',
	'HasInstance': 'has instance',
	'HasLastSubevent': 'has last subevent',
	'HasLexicalUnit': 'has lexical unit',
	'HasPrerequisite': 'has prerequisite',
	'HasProperty': 'has property',
	'HasSemType': 'has semantic type',
	'HasSubevent': 'has subevent',
	'HasSubframe': 'has subframe',
	'InstanceOf': 'is instance of',
	'IsA': 'is a',
	'IsCausativeOf': 'is causative of',
	'IsInchoativeOf': 'is inchoative of',
	'IsInheritedBy': 'is inherited by',
	'IsPerspectivizedIn': 'is perspectivized in',
	'IsPOSFormOf': 'is part-of-speech form of',
	'IsPrecededBy': 'is preceded by',
	'IsUsedBy': 'is used by',
	'LocatedNear': ' has location near',
	'MadeOf': 'is made of',
	'MannerOf': 'is a manner of',
	'MotivatedByGoal': 'is motivated by goal',
	'object': 'object',
	'OMWordnetOffset': 'has wordnet offset',
	'NotCapableOf': 'is not capable of',
	'NotDesires': 'does not desire',
	'NotHasProperty': 'does not have property',
	'PartOf': 'is part of',
	'PartOfSpeech': 'has part-of-speech of',
	'PerspectiveOn': 'is perspective on',
	'POSForm': 'is part-of-speech form',
	'Precedes': 'precedes',
	'PWordnetSynset': 'has wordnet synset',
	'ReceivesAction': 'has received action',
	'ReframingMapping': 'has reframing mapping',
	'RelatedTo': 'is related to',
	'st:RootType': 'has root type',
	'fe:RequiresFE': 'requires frame element',
	'subject': 'subject',
	'SeeAlso': 'see also',
	'SimilarTo': 'is similar to',
	'subClassOf': 'is subclass of',
	'SubframeOf': 'is subframe of',
	'st:SubType': 'is subtype of',
	'st:SuperType': 'is supertype of',
	'SymbolOf': 'is symbol of',
	'Synonym': 'is synonym of',
	'UsedFor': 'is used for',
	'Uses': 'uses',
	'DesireOf': 'desire of',
	'InheritsFrom': 'inherits from',
	'LocationOfAction': 'is location of action',
	'dbpedia/capital': 'is capital of',
	'dbpedia/field': 'is field of',
	'dbpedia/genre': 'is genre of',
	'dbpedia/genus': 'is genus of',
	'dbpedia/influencedBy': 'is influenced by',
	'dbpedia/knownFor': 'is known for',
	'dbpedia/language': 'has language',
	'dbpedia/leader': 'is leader of',
	'dbpedia/occupation': 'has occupation',
	'dbpedia/product': 'is product of',
	# new relations
	'rdfs:subClassOf': 'is subclass of',

	# ATOMIC Predicates:
	'at:xNeed': 'needs to',
	'at:xAttr': 'is',
	'at:xWant': 'want to',
	'at:oReact': 'will be',
	'at:oEffect': 'will',
	'at:xEffect': 'gets',
	'at:xIntent': 'wanted to be',
	'at:oWant': 'will',
	'at:xReact': 'will feel',
}
